name = "BRAF Halloween";       // Name of your mod
author = "BRAF Team & Ludwig"; // Affects Arma 3 Launcher, when the mod are loaded as local
logo = "logo_co.paa";          // Logo displayed in the main menu
logoOver = "logo_over_co.paa"; // When the mouse is over, in the main menu
tooltip = "BRAF Halloween";
tooltipOwned = "BRAF Team & Ludwig"; // Tool tip displayed when the mouse is left over, in the main menu
actionName = "BRAF Mod";
action = "https://brafmod.com.br";       // Website URL, that can be accessed from the expansions menu
overview = "BRAF Mod Halloween extras."; // Supports structured text
logoSmall = "logo_small.paa";            // Display in creative lists, next to the entities added by the mod